
AtlasLootCharDB = {
	["namespaces"] = {
		["WishList"] = {
			["global"] = {
				["data"] = {
					["Normal"] = {
						["Public Test Realm - MOP"] = {
							["Yep"] = {
								{
									{
										{
											0, -- [1]
											86945, -- [2]
											"", -- [3]
											"=q4=Hisek's Chrysanthemum Cape", -- [4]
											"=ds=#s4#", -- [5]
											"HoFZorlok#Heroic", -- [6]
										}, -- [1]
										{
											0, -- [1]
											89919, -- [2]
											"", -- [3]
											"=q4=Warbelt of Sealed Pods", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"HoFZorlok#Heroic", -- [6]
										}, -- [2]
										{
											0, -- [1]
											86944, -- [2]
											"", -- [3]
											"=q4=Articulated Legplates", -- [4]
											"=ds=#s11#, #a4#", -- [5]
											"HoFZorlok#Heroic", -- [6]
										}, -- [3]
										{
											0, -- [1]
											86946, -- [2]
											"", -- [3]
											"=q4=Vizier's Ruby Signet", -- [4]
											"=ds=#s13#", -- [5]
											"HoFZorlok#Heroic", -- [6]
										}, -- [4]
										{
											0, -- [1]
											86957, -- [2]
											"", -- [3]
											"=q4=Ring of the Bladed Tempest", -- [4]
											"=ds=#s13#", -- [5]
											"HoFTayak#Heroic", -- [6]
										}, -- [5]
										{
											0, -- [1]
											86955, -- [2]
											"", -- [3]
											"=q4=Waistplate of Overwhelming Assault", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"HoFTayak#Heroic", -- [6]
										}, -- [6]
										{
											0, -- [1]
											86956, -- [2]
											"", -- [3]
											"=q4=Windblade Talons", -- [4]
											"=ds=#s9#, #a4#", -- [5]
											"HoFTayak#Heroic", -- [6]
										}, -- [7]
										{
											0, -- [1]
											89921, -- [2]
											"", -- [3]
											"=q4=Pauldrons of the Broken Blade", -- [4]
											"=ds=#s3#, #a4#", -- [5]
											"HoFTayak#Heroic", -- [6]
										}, -- [8]
										{
											0, -- [1]
											86968, -- [2]
											"", -- [3]
											"=q4=Ring of the Shattered Shell", -- [4]
											"=ds=#s13#", -- [5]
											"HoFGaralon#Heroic", -- [6]
										}, -- [9]
										{
											0, -- [1]
											86967, -- [2]
											"", -- [3]
											"=q4=Necklace of Congealed Weaknesses", -- [4]
											"=ds=#s2#", -- [5]
											"HoFGaralon#Heroic", -- [6]
										}, -- [10]
										{
											0, -- [1]
											89923, -- [2]
											"", -- [3]
											"=q4=Garalon's Graven Carapace", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"HoFGaralon#Heroic", -- [6]
										}, -- [11]
										{
											0, -- [1]
											86966, -- [2]
											"", -- [3]
											"=q4=Garalon's Hollow Skull", -- [4]
											"=ds=#s1#, #a4#", -- [5]
											"HoFGaralon#Heroic", -- [6]
										}, -- [12]
										{
											0, -- [1]
											86979, -- [2]
											"", -- [3]
											"=q4=Impaling Treads", -- [4]
											"=ds=#s12#, #a4#", -- [5]
											"HoFMeljarak#Heroic", -- [6]
										}, -- [13]
										{
											0, -- [1]
											86980, -- [2]
											"", -- [3]
											"=q4=Cloak of Raining Blades", -- [4]
											"=ds=#s4#", -- [5]
											"HoFMeljarak#Heroic", -- [6]
										}, -- [14]
										{
											0, -- [1]
											86986, -- [2]
											"", -- [3]
											"=q4=Shoulderpads of Misshapen Life", -- [4]
											"=ds=#s3#, #a4#", -- [5]
											"HoFUnsok#Heroic", -- [6]
										}, -- [15]
										{
											0, -- [1]
											89928, -- [2]
											"", -- [3]
											"=q4=Legplates of Regal Reinforcement", -- [4]
											"=ds=#s11#, #a4#", -- [5]
											"HoFShekzeer#Heroic", -- [6]
										}, -- [16]
										{
											0, -- [1]
											86190, -- [2]
											"", -- [3]
											"=q4=Serrated Wasp Bracers", -- [4]
											"=ds=#s8#, #a4#", -- [5]
											"HoFTrash#Normal", -- [6]
										}, -- [17]
										{
											0, -- [1]
											86191, -- [2]
											"", -- [3]
											"=q4=Plated Locust Bracers", -- [4]
											"=ds=#s8#, #a4#", -- [5]
											"HoFTrash#Normal", -- [6]
										}, -- [18]
										{
											0, -- [1]
											87410, -- [2]
											"", -- [3]
											"=q4=Plans: Ornate Battleplate of the Master", -- [4]
											"=ds=#p2# (600)", -- [5]
											"Patternsilvl496#Normal", -- [6]
										}, -- [19]
										{
											0, -- [1]
											87408, -- [2]
											"", -- [3]
											"=q4=Plans: Unyielding Bloodplate", -- [4]
											"=ds=#p2# (600)", -- [5]
											"Patternsilvl496#Normal", -- [6]
										}, -- [20]
										{
											0, -- [1]
											87411, -- [2]
											"", -- [3]
											"=q4=Plans: Bloodforged Warfists", -- [4]
											"=ds=#p2# (600)", -- [5]
											"Patternsilvl496#Normal", -- [6]
										}, -- [21]
										{
											0, -- [1]
											87409, -- [2]
											"", -- [3]
											"=q4=Plans: Gauntlets of Battle Command", -- [4]
											"=ds=#p2# (600)", -- [5]
											"Patternsilvl496#Normal", -- [6]
										}, -- [22]
										{
											0, -- [1]
											87015, -- [2]
											"", -- [3]
											"=q4=Jasper Clawfeet", -- [4]
											"=ds=#s12#, #a4#", -- [5]
											"MSVTheStoneGuard#Heroic", -- [6]
										}, -- [23]
										{
											0, -- [1]
											87060, -- [2]
											"", -- [3]
											"=q4=Star-Stealer Waistguard", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"MSVTheStoneGuard#Heroic", -- [6]
										}, -- [24]
										{
											0, -- [1]
											87016, -- [2]
											"", -- [3]
											"=q4=Beads of the Mogu'shi", -- [4]
											"=ds=#s2#", -- [5]
											"MSVTheStoneGuard#Heroic", -- [6]
										}, -- [25]
										{
											0, -- [1]
											87025, -- [2]
											"", -- [3]
											"=q4=Bracers of Six Oxen", -- [4]
											"=ds=#s8#, #a4#", -- [5]
											"MSVFeng#Heroic", -- [6]
										}, -- [26]
										{
											0, -- [1]
											87024, -- [2]
											"", -- [3]
											"=q4=Nullification Greathelm", -- [4]
											"=ds=#s1#, #a4#", -- [5]
											"MSVFeng#Heroic", -- [6]
										}, -- [27]
										{
											0, -- [1]
											87026, -- [2]
											"", -- [3]
											"=q4=Cloak of Peacock Feathers", -- [4]
											"=ds=#s4#", -- [5]
											"MSVFeng#Heroic", -- [6]
										}, -- [28]
										{
											0, -- [1]
											89934, -- [2]
											"", -- [3]
											"=q4=Bonded Soul Bracers", -- [4]
											"=ds=#s8#, #a4#", -- [5]
											"MSVGarajal#Heroic", -- [6]
										}, -- [29]
										{
											0, -- [1]
											87035, -- [2]
											"", -- [3]
											"=q4=Sollerets of Spirit Splitting", -- [4]
											"=ds=#s12#, #a4#", -- [5]
											"MSVGarajal#Heroic", -- [6]
										}, -- [30]
										{
											0, -- [1]
											87036, -- [2]
											"", -- [3]
											"=q4=Soulgrasp Choker", -- [4]
											"=ds=#s2#", -- [5]
											"MSVGarajal#Heroic", -- [6]
										}, -- [31]
										{
											0, -- [1]
											87049, -- [2]
											"", -- [3]
											"=q4=Shoulderguards of the Unflanked", -- [4]
											"=ds=#s3#, #a4#", -- [5]
											"MSVSpiritKings#Heroic", -- [6]
										}, -- [32]
										{
											0, -- [1]
											87048, -- [2]
											"", -- [3]
											"=q4=Breastplate of the Kings' Guard", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"MSVSpiritKings#Heroic", -- [6]
										}, -- [33]
										{
											0, -- [1]
											89937, -- [2]
											"", -- [3]
											"=q4=Band of Bursting Novas", -- [4]
											"=ds=#s13#", -- [5]
											"MSVElegon#Heroic", -- [6]
										}, -- [34]
										{
											0, -- [1]
											87059, -- [2]
											"", -- [3]
											"=q4=Starcrusher Gauntlets", -- [4]
											"=ds=#s9#, #a4#", -- [5]
											"MSVElegon#Heroic", -- [6]
										}, -- [35]
										{
											0, -- [1]
											87071, -- [2]
											"", -- [3]
											"=q4=Jang-xi's Devastating Legplates", -- [4]
											"=ds=#s11#, #a4#", -- [5]
											"MSVWilloftheEmperor#Heroic", -- [6]
										}, -- [36]
										{
											0, -- [1]
											89941, -- [2]
											"", -- [3]
											"=q4=Chestguard of Eternal Vigilance", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"MSVWilloftheEmperor#Heroic", -- [6]
										}, -- [37]
										{
											0, -- [1]
											90506, -- [2]
											"", -- [3]
											"=q4=Bracers of Defiled Earth", -- [4]
											"=ds=#s8#, #a4#", -- [5]
											"ToESProtectors#Heroic", -- [6]
										}, -- [38]
										{
											0, -- [1]
											90507, -- [2]
											"", -- [3]
											"=q4=Deepwater Greatboots", -- [4]
											"=ds=#s12#, #a4#", -- [5]
											"ToESProtectors#Heroic", -- [6]
										}, -- [39]
										{
											0, -- [1]
											90509, -- [2]
											"", -- [3]
											"=q4=Kaolan's Withering Necklace", -- [4]
											"=ds=#s2#", -- [5]
											"ToESProtectors#Heroic", -- [6]
										}, -- [40]
										{
											0, -- [1]
											90508, -- [2]
											"", -- [3]
											"=q4=Shackle of Eversparks", -- [4]
											"=ds=#s2#", -- [5]
											"ToESProtectors#Heroic", -- [6]
										}, -- [41]
										{
											0, -- [1]
											87158, -- [2]
											"", -- [3]
											"=q4=Dread Shadow Ring", -- [4]
											"=ds=#s13#", -- [5]
											"ToESTsulong#Heroic", -- [6]
										}, -- [42]
										{
											0, -- [1]
											87186, -- [2]
											"", -- [3]
											"=q4=Patroller's Girdle of Endless Spring", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"ToESTsulong#Heroic", -- [6]
										}, -- [43]
										{
											0, -- [1]
											87185, -- [2]
											"", -- [3]
											"=q4=Protector's Girdle of Endless Spring", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"ToESTsulong#Heroic", -- [6]
										}, -- [44]
										{
											0, -- [1]
											89946, -- [2]
											"", -- [3]
											"=q4=Grasps of Serpentine Might", -- [4]
											"=ds=#s9#, #a4#", -- [5]
											"ToESTsulong#Heroic", -- [6]
										}, -- [45]
										{
											0, -- [1]
											87159, -- [2]
											"", -- [3]
											"=q4=Daybreak Drape", -- [4]
											"=ds=#s4#", -- [5]
											"ToESTsulong#Heroic", -- [6]
										}, -- [46]
										{
											0, -- [1]
											87171, -- [2]
											"", -- [3]
											"=q4=Cuirass of the Animated Protector", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"ToESLeiShi#Heroic", -- [6]
										}, -- [47]
										{
											0, -- [1]
											90433, -- [2]
											"", -- [3]
											"=q4=Mushan Rider's Collar", -- [4]
											"=ds=#s2#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [48]
										{
											0, -- [1]
											90431, -- [2]
											"", -- [3]
											"=q4=Saddlebinder Links", -- [4]
											"=ds=#s2#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [49]
										{
											0, -- [1]
											90436, -- [2]
											"", -- [3]
											"=q4=Circle of Scaled Fury", -- [4]
											"=ds=#s13#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [50]
										{
											0, -- [1]
											90438, -- [2]
											"", -- [3]
											"=q4=Signet of the Bandit Lord", -- [4]
											"=ds=#s13#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [51]
										{
											0, -- [1]
											90447, -- [2]
											"", -- [3]
											"=q4=Stompers of Vigorous Stomping", -- [4]
											"=ds=#s12#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [52]
										{
											0, -- [1]
											90446, -- [2]
											"", -- [3]
											"=q4=Silverspur Warboots", -- [4]
											"=ds=#s12#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [53]
										{
											0, -- [1]
											90455, -- [2]
											"", -- [3]
											"=q4=Greatbelt of Livid Fury", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [54]
										{
											0, -- [1]
											90456, -- [2]
											"", -- [3]
											"=q4=Cord of Crazed Strength", -- [4]
											"=ds=#s10#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [55]
										{
											0, -- [1]
											90424, -- [2]
											"", -- [3]
											"=q4=Ravaging Warrior's Chestplate", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [56]
										{
											0, -- [1]
											90425, -- [2]
											"", -- [3]
											"=q4=Carapace of Crushed Conviction", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [57]
										{
											0, -- [1]
											90414, -- [2]
											"", -- [3]
											"=q4=Greathelm of the Monstrous Mushan", -- [4]
											"=ds=#s1#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [58]
										{
											0, -- [1]
											90415, -- [2]
											"", -- [3]
											"=q4=Giantfoot Headguard", -- [4]
											"=ds=#s1#, #a4#", -- [5]
											"SalyisWarband#Normal", -- [6]
										}, -- [59]
										{
											0, -- [1]
											86915, -- [2]
											"", -- [3]
											"=q4=Helmet of the Lost Catacomb", -- [4]
											"=ds=#s1#, #a4#", -- [5]
											"T14DeathKnightDPS#Normal", -- [6]
										}, -- [60]
										{
											0, -- [1]
											86917, -- [2]
											"", -- [3]
											"=q4=Pauldrons of the Lost Catacomb", -- [4]
											"=ds=#s3#, #a4#", -- [5]
											"T14DeathKnightDPS#Normal", -- [6]
										}, -- [61]
										{
											0, -- [1]
											86913, -- [2]
											"", -- [3]
											"=q4=Breastplate of the Lost Catacomb", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"T14DeathKnightDPS#Normal", -- [6]
										}, -- [62]
										{
											0, -- [1]
											86914, -- [2]
											"", -- [3]
											"=q4=Gauntlets of the Lost Catacomb", -- [4]
											"=ds=#s9#, #a4#", -- [5]
											"T14DeathKnightDPS#Normal", -- [6]
										}, -- [63]
										{
											0, -- [1]
											86916, -- [2]
											"", -- [3]
											"=q4=Greaves of the Lost Catacomb", -- [4]
											"=ds=#s11#, #a4#", -- [5]
											"T14DeathKnightDPS#Normal", -- [6]
										}, -- [64]
										{
											0, -- [1]
											86920, -- [2]
											"", -- [3]
											"=q4=Faceguard of the Lost Catacomb", -- [4]
											"=ds=#s1#, #a4#", -- [5]
											"T14DeathKnightTank#Normal", -- [6]
										}, -- [65]
										{
											0, -- [1]
											86922, -- [2]
											"", -- [3]
											"=q4=Shoulderguards of the Lost Catacomb", -- [4]
											"=ds=#s3#, #a4#", -- [5]
											"T14DeathKnightTank#Normal", -- [6]
										}, -- [66]
										{
											0, -- [1]
											86918, -- [2]
											"", -- [3]
											"=q4=Chestguard of the Lost Catacomb", -- [4]
											"=ds=#s5#, #a4#", -- [5]
											"T14DeathKnightTank#Normal", -- [6]
										}, -- [67]
										{
											0, -- [1]
											86919, -- [2]
											"", -- [3]
											"=q4=Handguards of the Lost Catacomb", -- [4]
											"=ds=#s9#, #a4#", -- [5]
											"T14DeathKnightTank#Normal", -- [6]
										}, -- [68]
										{
											0, -- [1]
											86921, -- [2]
											"", -- [3]
											"=q4=Legguards of the Lost Catacomb", -- [4]
											"=ds=#s11#, #a4#", -- [5]
											"T14DeathKnightTank#Normal", -- [6]
										}, -- [69]
									}, -- [1]
									["info"] = {
										["name"] = "DK T14",
										["icon"] = "INTERFACE\\ICONS\\Spell_Deathknight_BloodPresence",
										["default"] = false,
									},
								}, -- [1]
							},
						},
					},
				},
			},
		},
	},
	["profileKeys"] = {
		["Yep - Public Test Realm - MOP"] = "Yep - Public Test Realm - MOP",
	},
	["AtlasLootVersion"] = "70703",
}
